version: '3.9'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dustfi_docs
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - dustfi_network

networks:
  dustfi_network:
    external: true